[package]
name = "aparan"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.23.1", features = ["full"] }
aparan-macros = { path = "../aparan-macros" }

[package.metadata.nix]
build = true
