[package]
name = "aparan-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.66"

quote = "1.0.32"

syn = { version = "2.0.31", features = ["full"] }


[lib]
proc-macro = true

[dev-dependencies]
aparan = { path = "../aparan" }
