[package]
name = "aparan-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.56"

quote = "1.0.26"

syn = { version = "1.0.109", features = ["full"] }


[lib]
proc-macro = true

[dev-dependencies]
aparan = { path = "../aparan" }
